async function main() {}

try {
  await main()
} catch (error) {
  console.log(error)
}
